trigger:
- main

pool:
  name: Self-Host

steps:
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      repository: 'simplyevents' 
      command: 'build'        
      Dockerfile: '**/Dockerfile'
      tags: |
        latest
        $(Build.BuildId)      
